In [25]:
import copy
import nltk
from nltk import word_tokenize, sent_tokenize
import numpy as np
import pandas as pd
import ast

# Restaurants 8K

with open('C:/Users/kleop/Documents/repos/Exercises/My_chatbot/hw1/span_extraction/restaurant8k/train_0.json', 'r') as f:
    data = json.load(f)

restaurants = pd.DataFrame(data)

to do's..: extract the value of each key 'text' in each row of the column "unserInput" in the dataframe

# DSTC8

In [19]:
with open('C:/Users/kleop/Documents/repos/Exercises/My_chatbot/hw1/span_extraction/dstc8/Buses_1/train_0.json', 'r') as f:
    data = json.load(f)

buses = pd.DataFrame(data)

In [31]:
def extract_text(row):
    return row['text']

# Apply the function to the 'UserInput' column
buses['Text'] = buses['userInput'].apply(extract_text)

print(buses['Text'])

0          Can you help me out and look for a bus for me?
1                               I want to visit New York.
2       I am leaving out from Washington on the 11th o...
3       What is the bus station that I will leave from...
4                                      Sounds fine to me.
                              ...
1128    What would be the name of the bus station I wo...
1129    Are there any other buses available? Just for ...
1130                         Are there any other options?
1131               That it exactly what I am looking for.
1132    No, I just wanted to gather some information, ...
Name: Text, Length: 1133, dtype: object

In [8]:
with open('C:/Users/kleop/Documents/repos/Exercises/My_chatbot/hw1/span_extraction/dstc8/Events_1/train_0.json', 'r') as f:
    data = json.load(f)

events = pd.DataFrame(data)

In [32]:
# Define a function to extract the text content from the 'userInput' column
def extract_text(row):
    return row['userInput']['text']

# Apply the function to each row of the DataFrame to extract the text content
events = events.apply(extract_text)

# Now you can work with the 'text_content' column which contains the content of the 'text' key
print(events)

KeyError: 'userInput'

In [10]:
with open('C:/Users/kleop/Documents/repos/Exercises/My_chatbot/hw1/span_extraction/dstc8/Homes_1/train_0.json', 'r') as f:
    data = json.load(f)

homes = pd.DataFrame(data)

In [11]:
homes

,userInput,context,id,splitKey,labels
0,{'text': 'I want apartment where pets are allo...,{},31_000000,1.0,NaN
1,{'text': 'one bed room is enough'},{'requestedSlots': ['number_of_beds']},31_000002,1.0,NaN
2,{'text': 'Fremont will be fine'},{'requestedSlots': ['area']},31_000004,1.0,"[{'slot': 'area', 'valueSpan': {'endIndex': 7}}]"
3,{'text': 'Please find some other apartments'},{},31_000006,1.0,NaN
4,{'text': 'can you find some other with one bat...,{},31_000008,1.0,NaN
...,...,...,...,...,...
2059,"{'text': 'Ok, I would like to schedule a visit...",{},32_000108,1.0,"[{'slot': 'visit_date', 'valueSpan': {'startIn..."
2060,"{'text': 'No, actually, I need to make it for ...",{},32_0001010,1.0,"[{'slot': 'visit_date', 'valueSpan': {'startIn..."
2061,"{'text': 'Yes, that is correct. Also, are pets...",{},32_0001012,1.0,NaN
2062,"{'text': 'Ok, that is great.'}",{},32_0001014,1.0,NaN
2063,"{'text': 'No, that is all. Thank you.'}",{},32_0001016,1.0,NaN

In [12]:
with open('C:/Users/kleop/Documents/repos/Exercises/My_chatbot/hw1/span_extraction/dstc8/RentalCars_1/train_0.json', 'r') as f:
    data = json.load(f)

rental_cars = pd.DataFrame(data)

In [13]:
rental_cars

,userInput,context,id,splitKey,labels
0,{'text': 'Book me a rental car.'},{},23_000170,1.0,NaN
1,{'text': 'I'll pick it up around 10:30 in the ...,"{'requestedSlots': ['pickup_time', 'dropoff_da...",23_000172,1.0,"[{'slot': 'dropoff_date', 'valueSpan': {'start..."
2,{'text': 'I'll pick it up in New York on March...,"{'requestedSlots': ['pickup_city', 'pickup_dat...",23_000174,1.0,"[{'slot': 'pickup_city', 'valueSpan': {'startI..."
3,{'text': 'Sounds good'},{},23_000176,1.0,NaN
4,{'text': 'No not now'},{},23_000178,1.0,NaN
...,...,...,...,...,...
869,{'text': 'Sounds good.'},{},23_0012012,1.0,NaN
870,{'text': 'Yes. I'll reserve that car.'},{},23_0012014,1.0,NaN
871,"{'text': 'Yes, sounds good to me.'}",{},23_0012016,1.0,NaN
872,{'text': 'Thanks so much. I appreciate it.'},{},23_0012018,1.0,NaN
873,"{'text': 'Nope, thanks for your help.'}",{},23_0012020,1.0,NaN